### ISSUE TITLE
Link to other Free Software lists

### ISSUE THREAD

**Issue by nodiscc** [johnjago/awesome-free-software#11]
Hi, thanks for building this list!

Would you like to add https://github.com/Kickball/awesome-selfhosted as a complementary list (maybe in a new `Other lists` section)? I am a maintainer and we only accept Free Software in the main list (there is a separate non-free page). https://github.com/n1trux/awesome-sysadmin is also entirely FOSS.

So something like

### Other software lists

 * [awesome-selfhosted](https://github.com/Kickball/awesome-selfhosted) - Free Software network services and Web applications
 * [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) - Free Software for system administrators

Thanks in advance

**Comment by johnjago** [comment]
Thank you for the suggestion. This is a great idea. I wonder why I did not think of it earlier.

I have created the new category: https://github.com/johnjago/awesome-free-software/blob/master/README.md#other-lists

Anyone, feel free to create a pull request or make an issue if you find other related lists to add.

**Comment by nodiscc** [comment]
Thanks, I think you can find more lists at https://github.com/sindresorhus/awesome. There's also https://github.com/nodiscc/awesome-linuxaudio and https://wiki.archlinux.org/index.php/List_of_applications (not strictly Free Software)
