### ISSUE TITLE
Misc section?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [johnjago/Awesome-Free-Software#3]
I've noticed some weird placements, like VLC in the graphics section and qBittorrent in the file management section, presumably because there is no more appropriate section to put them in.

So, what I'm proposing is adding a new section called `Miscellaneous` where the software which doesn't have its own category yet should go in.

**Comment by johnjago** [comment]
Thank you for the suggestion. I added a `Miscellaneous` section and placed VLC and qBittorrent in it for now. I have not used any other multimedia players or torrent clients, and I did not want to place those two in categories by themselves. Hopefully people who use other ones can add them and eventually populate new sections just for multimedia players, etc.
