### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by legodude17** [johnjago/awesome-free-software#7]
Some things to add:
 - Under IDE's, Visual Studio Code
 - Under Browsers, Chromium
 - Under graphics, Piskel, Inkscape, Pinta

**Comment by johnjago** [comment]
Visual Studio Code binaries are actually under a proprietary Microsoft license: https://code.visualstudio.com/license. Only the source code is released under the MIT license, which is kind of deceptive. I would not feel comfortable adding this piece of software to the list.

However, the others are great suggestions! I have added them.

**Comment by legodude17** [comment]
Thank you for taking my suggestions!
